apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-health
  namespace: psl
  labels:
    app.kubernetes.io/name: k8s-health
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-health
  template:
    metadata:
      name: k8s-health
      labels:
        app.kubernetes.io/name: k8s-health
    spec:
      serviceAccountName: k8s-health
      containers:
        - name: k8s-health
          # image: <registry>/psl/k8s-health:<version>
          # image: <registry>/flakybitnet/psl-k8s-health:<version>
          image: harbor.flakybit.net/psl/k8s-health:2.0.0
          envFrom:
            - configMapRef:
                name: k8s-health
          env:
            - name: PSL_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 16Mi
            limits:
              cpu: 500m
              memory: 32Mi
