apiVersion: v1
kind: Service
metadata:
  name: k8s-health
  namespace: psl
  labels:
    app.kubernetes.io/name: k8s-health
spec:
  type: ClusterIP
  internalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: k8s-health
  ports:
    - name: http
      port: 8080
      targetPort: http
