apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lock
  namespace: psl
  labels:
    app.kubernetes.io/name: lock
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lock
  template:
    metadata:
      name: lock
      labels:
        app.kubernetes.io/name: lock
    spec:
      containers:
        - name: lock
          # image: <registry>/psl/lock:<version>
          # image: <registry>/flakybitnet/psl-lock:<version>
          image: harbor.flakybit.net/psl/lock:2.0.0
          envFrom:
            - configMapRef:
                name: lock
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 8Mi
            limits:
              cpu: 500m
              memory: 16Mi
