apiVersion: v1
kind: Service
metadata:
  name: lock
  namespace: psl
  labels:
    app.kubernetes.io/name: lock
spec:
  type: ClusterIP
  internalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: lock
  ports:
    - name: http
      port: 8888
      targetPort: http
